# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d158558eaf4894a7bb93dc16f62e947c21635bf6cacd2c8fa8f186e29e4a5401ca8eee153e373b68f158eeb88114dee5cf9e7ada669b9e79b2e46a4aab24405

test:
  secret_key_base: 9b05868f155aa1701f4610a6c7da4fb415437dbd33d40dafe0722956832c036b112d86451bfb20a35b5d2fa88dfceb75a8b3b0d8203e5ee73a717e6de42ad167

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
